import type { V2FateType } from "./types";

export const v2FateTypes: V2FateType[] = [
  {
    id: "phoenix",
    name: "凤仪天成",
    verdict: "天生凤骨，不争而临天下",
    primary: "social",
    secondary: "ambition",
    summary: "你是那种站在人群中不需要说话就会被看见的人。你的难题不是如何被看见，而是被看见之后如何不被定义。",
    corePsychology: "高自我效能、高社会感知、低外显攻击性。你不靠攻击确立地位，存在本身就是权力信号。",
    surfaceStyle: "端庄、从容、界线感强，不卑不亢。",
    hiddenFear: "你最怕的不是被打败，而是被人发现你也会害怕、犹豫、不知道怎么办。",
    survivalStyle: "靠气质和分寸感立足，用不出错积累不可替代性。",
    emotionalWeakness: "你不习惯示弱，也不擅长挽留。真正重要的人面前，反而不知道如何开口。",
    powerPath: "被选择。你不追逐权力，但权力会向你靠近。",
    relationshipPattern: "君子之交，淡而有度。距离感本身就是筛选。",
    modernMirror: "像职场中的气质型女领导，不常发火，但所有人都在猜她的标准。",
    shareQuote: "这宫里，有一种赢法叫——不出错，不低头，不让任何人看穿你的下一步。",
    posterQuote: "有些人不用说话，站在那里就是规矩。",
  },
  {
    id: "strategist",
    name: "冷宫谋后",
    verdict: "忍到极致，便是翻盘",
    primary: "survival",
    secondary: "strategy",
    summary: "你从不争第一口气，因为你争的是最后一口气。别人以为你忍让，其实你在数步子。",
    corePsychology: "高延迟满足、高威胁敏感度、强忍耐力。情绪不是没有，而是被存成未来的燃料。",
    surfaceStyle: "看起来无害、听话、没有脾气。",
    hiddenFear: "你怕的不是受苦，而是受的苦没有回报。",
    survivalStyle: "不冒头、不站队、不急着被记住。你的武器是时间。",
    emotionalWeakness: "忍得太久，有时会忘了自己真正想要什么。",
    powerPath: "逆袭。不是靠一次翻盘，而是靠每次别人退一步时你往前挪半寸。",
    relationshipPattern: "严格筛选。圈子很小，但每个留下来的人都很深。",
    modernMirror: "像在高压行业里从基层熬上来的女性，知道什么时候该忍，什么时候该换一口气。",
    shareQuote: "你笑我低着头走路，却不知道我低头的时候，在数你走过的每一步。",
    posterQuote: "有些人不是在忍——是在等。",
  },
  {
    id: "minister",
    name: "玉面权臣",
    verdict: "不急着亮牌，先知道牌从哪里来",
    primary: "strategy",
    secondary: "ambition",
    summary: "你不急着赢眼前这一局，你更在意谁在发牌、谁在换牌、谁假装没有牌。",
    corePsychology: "高信息敏感、高延迟判断、高目标感。你习惯把人和局分开看。",
    surfaceStyle: "温和、冷静、像个可靠的人。",
    hiddenFear: "你怕失控，怕自己在信息不足时被迫下注。",
    survivalStyle: "用信息换空间，用判断换机会。",
    emotionalWeakness: "太会分析，会让你在真正需要感受的时候仍然选择计算。",
    powerPath: "暗中布局，步步为营。",
    relationshipPattern: "你不是不信人，只是更相信经过验证的关系。",
    modernMirror: "像组织里真正掌握信息流的人，不一定职位最高，却知道关键门在哪里。",
    shareQuote: "你以为我输的时候，我还没开始。你以为我赢的时候，我已经在走下一步了。",
    posterQuote: "真正的牌，从来不在桌面上。",
  },
  {
    id: "observer",
    name: "烟雨贵人",
    verdict: "看得太清楚的人，活得最累",
    primary: "strategy",
    secondary: "emotion",
    summary: "你看得见局，也看得见人心里最软的地方。你并不天真，只是不愿把清醒变成冷酷。",
    corePsychology: "高心智化能力、高情绪真实、高克制。你知道真相，但不总是愿意使用真相。",
    surfaceStyle: "安静、温柔、像什么都没看破。",
    hiddenFear: "你怕自己有一天也会把别人当成棋子。",
    survivalStyle: "看破不说破，退半步保留余地。",
    emotionalWeakness: "清醒让你免于受骗，也让你很难真正轻松。",
    powerPath: "以退为进，不把权力握得太满。",
    relationshipPattern: "你会给人留余地，也会给自己留出口。",
    modernMirror: "像最会读空气的人，知道很多话不能说，很多关系不能戳破。",
    shareQuote: "我不是不懂，只是有些真相，说出口就没有回头路。",
    posterQuote: "看破，是另一种沉默。",
  },
  {
    id: "lonePhoenix",
    name: "金枝孤凤",
    verdict: "锋利是真，孤独也是真",
    primary: "ambition",
    secondary: "emotion",
    summary: "你不愿讨好，也不愿为了安全把自己磨圆。你宁愿被误解，也不愿活成别人喜欢的样子。",
    corePsychology: "高自我一致性、高尊严需求、高行动冲动。你在压力下更容易选择正面表达。",
    surfaceStyle: "锋利、真实、不太会装。",
    hiddenFear: "你怕自己终于赢了，却发现身边一个人都没有。",
    survivalStyle: "用锋利保护真实，用行动打破僵局。",
    emotionalWeakness: "你太需要自己问心无愧，因此有时低估现实代价。",
    powerPath: "主动出击，不接受被安排的位置。",
    relationshipPattern: "你要的不是热闹，而是能承受你真实的人。",
    modernMirror: "像职场里敢说真话的人，不一定最安全，但很难被彻底驯服。",
    shareQuote: "我怕输，但我更怕从此不敢看自己。",
    posterQuote: "宁可孤独，不可失真。",
  },
  {
    id: "hiddenBond",
    name: "暗香棋子",
    verdict: "善意不是软弱，是另一种暗线",
    primary: "survival",
    secondary: "emotion",
    summary: "你不一定站在明处，却能在无人注意的地方留下关系和善意。你相信人心有时比权力更长久。",
    corePsychology: "高生存敏感、高共情、高关系记忆。你用温柔建立隐形网络。",
    surfaceStyle: "低调、柔软、不争。",
    hiddenFear: "你怕自己的善意被当成廉价，也怕有一天没人记得你做过什么。",
    survivalStyle: "以退为进，以善意换取长期安全。",
    emotionalWeakness: "你容易替别人考虑太多，忘了自己也需要被保护。",
    powerPath: "不靠争夺，而靠被人记住。",
    relationshipPattern: "你的人情线藏得很深，但关键时刻会有人回头。",
    modernMirror: "像团队里总在补位的人，看似不起眼，却让所有事情不至于散掉。",
    shareQuote: "我不是没有锋芒，只是把它藏在了不伤人的地方。",
    posterQuote: "暗香也能成路。",
  },
  {
    id: "beauty",
    name: "红颜祸水",
    verdict: "被看见，不等于被理解",
    primary: "social",
    secondary: "emotion",
    summary: "你容易成为目光的中心，却不一定被真正理解。别人看见你的吸引力，却常常忽略你的选择和疼痛。",
    corePsychology: "高社会吸引、高情绪需求、高被误读风险。你渴望被看见，也渴望被认真对待。",
    surfaceStyle: "明艳、敏感、有存在感。",
    hiddenFear: "你怕别人只爱你的光，不在乎光背后的你。",
    survivalStyle: "用吸引力获得空间，但也不断和误解周旋。",
    emotionalWeakness: "你太容易被一句真正的理解击中。",
    powerPath: "从被观看到主动定义自己。",
    relationshipPattern: "你能吸引很多人，却只想被少数人真正看懂。",
    modernMirror: "像现实中外表、表达或魅力很强的女性，常被投射，也常被误解。",
    shareQuote: "你看见我的光，却未必看见我一路怎么走到这里。",
    posterQuote: "被看见之后，还要被理解。",
  },
  {
    id: "actor",
    name: "笑里藏刀",
    verdict: "面具戴久了，也会长成脸",
    primary: "social",
    secondary: "strategy",
    summary: "你知道什么时候该笑，什么时候该沉默，什么时候该把一句话递给该听见的人。你的面具不是虚伪，是生存工具。",
    corePsychology: "高社会适应、高信息中介、高角色切换能力。你能在关系之间移动而不立刻暴露自己。",
    surfaceStyle: "好相处、会说话、懂分寸。",
    hiddenFear: "你怕有一天没人知道面具后面真正的你是什么样。",
    survivalStyle: "用笑意降低敌意，用信息换取位置。",
    emotionalWeakness: "你太习惯表演，真正受伤时也会先摆出没事的样子。",
    powerPath: "成为关系网络里的信息节点。",
    relationshipPattern: "你能和很多人相处，但真正卸下面具的人很少。",
    modernMirror: "像职场或社交场里最会周旋的人，看似轻松，其实一直在处理复杂信号。",
    shareQuote: "我笑，不代表我没看见；我不说，不代表我没记住。",
    posterQuote: "笑意之下，也有刀锋。",
  },
];
